import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx,mdx}',
    './components/**/*.{ts,tsx}',
    './data/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#0752B7',
        'primary-600': '#3D72BA',
        'primary-500': '#4E89C5',
        'primary-400': '#7089C0',
        'primary-100': '#D3DEF6',
        'on-primary': '#ffffff',
        'primary-container': '#D3DEF6',
        'on-primary-container': '#053577',
        'accent': '#5DE1E6',
        'accent-600': '#58C2C4',
        'accent-500': '#57A8CE',
        'accent-100': '#CDF6FB',
        'accent-50': '#E6FDFF',
        'on-accent': '#053577',
        'secondary': '#64748b',
        'on-secondary': '#ffffff',
        'secondary-container': '#f1f5f9',
        'on-secondary-container': '#334155',
        'surface': '#ffffff',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'outline': '#94a3b8',
        'outline-variant': '#cbd5e1',
        'background': '#ffffff',
        'on-background': '#0f172a',
        'surface-tint': '#0752B7',
        'inverse-surface': '#0f172a',
        'inverse-on-surface': '#f1f5f9',
        'inverse-primary': '#8fb1df',
        'surface-bright': '#f8fafc',
        'surface-dim': '#e2e8f0',
        'error': '#ef4444',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#991b1b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
